<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Konnektr.Npgsql.Age</PackageId>
    <PackageTags>postgres;postgresql;apache-age;graph</PackageTags>
    <Authors>Niko Raes, Emmanuel Allison</Authors>
    <Description>A plugin that extends Npgsql to enable using npgsql the ApacheAge extension for PostgreSQL.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
    <LangVersion>9.0</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>Npgsql.Age</Title>
    <RepositoryUrl>https://github.com/konnektr-io/npgsql-age</RepositoryUrl>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.300" PrivateAssets="All" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

</Project>
